version: '3'
networks:
    my_network:
services:
  postgresdb:
    image: postgres
    restart: always
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker 
    volumes:
      - pgadmin:/var/lib/postgresql/data
    networks:
      - my_network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports: 
  #     - 80:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=user@domain.com
  #     - PGADMIN_DEFAULT_PASSWORD=SuperSecret
  #   depends_on:
  #     - postgresdb
  #   networks:
  #     - my_network

  webscraper:
    build: .
    volumes:
      - ./csv:/app/csv
    depends_on:
      - postgresdb
    networks:
      - my_network


volumes:
  pgadmin:
